apiVersion: v1
kind: Service
metadata:
  namespace: promise
  name: test-service-inner-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 31002
      name: http-port
      targetPort: 31002
  selector:
    app: test-service