apiVersion: v1
kind: Service
metadata:
  namespace: promise
  name: promise-recommend-inner-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8888
      name: http-port
      targetPort: 8888
  selector:
    app: promise-recommend