apiVersion: v1
kind: Service
metadata:
  namespace: promise
  name: promise-recommend-web-service
spec:
  type: NodePort
  ports:
    - name: web
      port: 8888
      targetPort: 8888
      nodePort: 31888
  selector:
    app: promise-recommend