import {
  ElTabPane,
  ElRadio,
  ElRadioGroup,
  ElTabs,
  ElDialog,
  ElInput,
  ElDatePicker,
  ElButton,
  ElDivider,
  ElSelect,
  ElOption,
  ElOptionGroup,
  ElTooltip,
  ElIcon,
  ElUpload,
  ElNotification,
  ElPopover,
  ElCarousel,
  ElCarouselItem,
  ElForm,
  ElFormItem,
  ElCascader,
  ElTable,
  ElTableColumn,
  ElSwitch,
  ElRate,
  ElPagination,
  ElInputNumber,
  ElCheckbox,
} from "element-plus";

const components = [
  ElRadio,
  ElRadioGroup,
  ElTabPane,
  ElTabs,
  ElDialog,
  ElInput,
  ElDatePicker,
  ElButton,
  ElDivider,
  ElSelect,
  ElOption,
  ElOptionGroup,
  ElTooltip,
  ElIcon,
  ElUpload,
  ElNotification,
  ElPopover,
  ElCarousel,
  ElCarouselItem,
  ElForm,
  ElFormItem,
  ElCascader,
  ElTable,
  ElTableColumn,
  ElSwitch,
  ElRate,
  ElPagination,
  ElInputNumber,
  ElCheckbox,
];
export default function registerElement(app) {
  components.forEach((component) => {
    app.component(component.name, component);
  });
}
