apiVersion: v1
kind: Service
metadata:
  name: redis-web-service
  namespace: redis
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379
  selector:
    app: redis