---
##Redis的配置文件
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  namespace: redis
  labels:
    app: redis
data:
  redis.conf: |-
    dir /data
    port 6379
    bind 0.0.0.0
    save 900 1
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    appendonly yes
    appendfsync everysec
    auto-aof-rewrite-percentage 100
    aof-use-rdb-preamble yes
    protected-mode no
    pidfile /data/redis-6379.pid
    maxmemory 256MB
    maxmemory-policy allkeys-lfu
    logfile ""
    requirepass xxxxxxxxx
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: system-init
          image: busybox:1.32
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - "echo 2048 > /proc/sys/net/core/somaxconn && echo never > /sys/kernel/mm/transparent_hugepage/enabled"
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - mountPath: /sys
              name: sys
      containers:
        - name: redis
          image: redis:6.0.10
          command:
            - "sh"
            - "-c"
            - "redis-server /usr/local/etc/redis/redis.conf"
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: 750Mi
            requests:
              memory: 128Mi
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /usr/local/etc/redis/redis.conf
              name: config
              subPath: redis.conf
      volumes:
        - name: config
          configMap:
            name: redis-config
        - name: sys
          hostPath:
            path: /sys
        - name: data
          nfs:
            path: /root/share/redis/data
            server: $(YOU_SERVER_IP)