apiVersion: v1
kind: Service
metadata:
  namespace: promise
  name: user-service-web-service
spec:
  type: NodePort
  ports:
    - name: web
      port: 31003
      targetPort: 31003
      nodePort: 30903
      protocol: TCP
  selector:
    app: user-service