apiVersion: v1
kind: Service
metadata:
  namespace: promise
  name: user-service-inner-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 31003
      name: http-port
      targetPort: 31003
  selector:
    app: user-service