apiVersion: v1
kind: Service
metadata:
  namespace: promise
  name: publish-service-web-service
spec:
  type: NodePort
  ports:
    - name: web
      port: 31001
      targetPort: 31001
      nodePort: 30901
      protocol: TCP
  selector:
    app: publish-service